build:
	bun build app/maze/GrowingTree.ts --minify --outfile app/maze/index.js --production --target=browser --format=iife

watch:
	bun build app/maze/GrowingTree.ts --outfile app/maze/index.js --target=browser --format=iife --watch
